language: java
sudo: false
install: true

dist: trusty
jdk:
  - oraclejdk8

branches:
  except:
    - travis-pre-release

addons:
  sonarcloud:
    organization: adnovum
    token:
      secure: "OZAjVsFt2MICZns2lODx1O4306p9HtAk3Ojt3pxME6mMnRceVEIvMHaOzwzWYdidmwUKIWg7rFaMaPPkfJjW1bU8eDgWkqoBtikATOIlFoT+jI+5KHeujUj90ymqY4FAorTJpXLg4hpxmiqWYjNOy4rPh+/hu650yKKKZJ6P53c="

env:
  global:
    - GITHUB_TOKEN:  &GITHUB_TOKEN
        secure: "djo5iqoDyFU/Aa7hVrKPxuRJC/jwSZDll8KdJtaDN++VJ+iGLKBhSrJggUBXL54C7eCTjcodlSv+6K1owaflpqrfnJW3WkmmecHK0UTAT+ouYtyTHjIY7ltaBgM1pCrhGcqMgjYbPxJuxfl7lKP1ZiFRvA/kB0SoCvatfFtUxzI="

script:
  # Run this first, because 'verify' builds the project and runs the auto-formatting.
  # But we want to detect commits that don't adhere to the format. E.g. if someone
  # makes last-minute code changes without rebuilding it locally (which would auto-format).
  - mvn com.coveo:fmt-maven-plugin:check -B -e -V
  - mvn verify -DbuildVersion=$TRAVIS_BUILD_NUMBER -B -e -V
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn sonar:sonar -Dsonar.projectKey=adnovum_sonar-build-breaker DbuildVersion=$TRAVIS_BUILD_NUMBER -B -e -V'

before_deploy:
  - .travis/prepare_pre_release.sh
deploy:
  provider: releases
  api_key: *GITHUB_TOKEN
  file_glob: true
  file: target/sonar-build-breaker-plugin-*.jar
  skip_cleanup: true
  prerelease: true
  overwrite: true
  name: Travis Pre-Release Build
  body: Automatic pre-release build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  on:
    repo: adnovum/sonar-build-breaker
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
